=== khyatimahendru/udmi/schema/events_system.json
{
  "$udmi_version": "1.5.2",
  "title": "System Events",
  "description": "Used for system events such as logging. [System Event Documentation](../docs/messages/system.md#event)",
  "$section": "Messages",
  "type": "object",
  "$schema": "http://json-schema.org/draft-07/schema#",
  "additionalProperties": false,
  "properties": {
    "timestamp": {
      "description": "RFC 3339 UTC timestamp the event payload was generated",
      "type": "string",
      "format": "date-time",
      "examples": ["2019-01-17T14:02:29.364Z"]
    },
    "version": {
      "description": "Version of the UDMI schema",
      "type": "string"
    },
    "upgraded_from": {
      "description": "Original version of schema pre-upgrade",
      "type": "string"
    },
    "last_config": {
      "description": "Last config received",
      "type": "string",
      "format": "date-time",
      "examples": ["2019-01-17T14:02:29.364Z"]
    },
    "logentries": {
      "type": "array",
      "items": {
        "$ref": "file:entry.json"
      }
    },
    "event_no": {
      "description": "Sequence number for this event",
      "type": "integer"
    },
    "metrics": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "mem_total_mb": {
          "type": "number"
        },
        "mem_free_mb": {
          "type": "number"
        },
        "store_total_mb": {
          "type": "number"
        },
        "store_free_mb": {
          "type": "number"
        },
        "system_load": {
          "type": "number"
        }
      }
    },
    "credentials": {
      "type": "array",
      "items": {
        "properties": {
          "key_format": {
            "description": "The key type used for cloud communication.",
            "enum": [
              "PASSWORD",
              "ES256",
              "ES256_X509",
              "RS256",
              "RS256_X509"
            ]
          },
          "key_data": {
            "type": "string"
          }
        }
      }
    }
  },
  "required": [
    "timestamp",
    "version"
  ]
}

=== khyatimahendru/udmi/validator/sequences/blob_update_unreachable_url/events_system.json
{
  "event_no" : 4,
  "last_config" : "TIMESTAMP",
  "logentries" : [ {
    "message" : "success",
    "category" : "system.config.receive",
    "timestamp" : "TIMESTAMP",
    "level" : 100
  }, {
    "message" : "State update defer -1042ms",
    "category" : "device.log",
    "timestamp" : "TIMESTAMP",
    "level" : 100
  }, {
    "message" : "success",
    "category" : "system.config.parse",
    "timestamp" : "TIMESTAMP",
    "level" : 100
  }, {
    "message" : "Device AHU-1 config handler",
    "category" : "device.log",
    "timestamp" : "TIMESTAMP",
    "level" : 200
  }, {
    "message" : "State update AHU-1 (blob_update_unreachable_url)",
    "detail" : "{\n  \"timestamp\" : \"TIMESTAMP\",\n      \"level\" : 100\n    }\n  },\n  \"discovery\" : {\n    \"families\" : { }\n  },\n  \"localnet\" : {\n    \"families\" : {\n      \"ether\" : {\n        \"addr\" : \"42:01:ac:11:23:ac\"\n      },\n      \"ipv4\" : {\n        \"addr\" : \"172.17.35.172\"\n      },\n      \"vendor\" : {\n        \"addr\" : \"28179023\"\n      },\n      \"bacnet\" : {\n        \"addr\" : \"27312\"\n      }\n    }\n  },\n  \"pointset\" : {\n    \"points\" : {\n      \"filter_alarm_pressure_status\" : {\n        \"units\" : \"No-units\"\n      },\n      \"filter_differential_pressure_setpoint\" : {\n        \"units\" : \"Bars\",\n        \"value_state\" : \"applied\"\n      },\n      \"filter_differential_pressure_sensor\" : {\n        \"units\" : \"Degrees-Celsius\"\n      }\n    }\n  }\n}",
    "category" : "device.log",
    "timestamp" : "TIMESTAMP",
    "level" : 100
  }, {
    "message" : "Config update AHU-1 (blob_update_unreachable_url)",
    "detail" : "{\n  \"timestamp\" : \"TIMESTAMP\"\n    },\n    \"testing\" : {\n      \"sequence_name\" : \"blob_update_unreachable_url\",\n      \"transaction_id\" : \"RC:c1b619.00000007\",\n      \"config_base\" : 131\n    }\n  },\n  \"discovery\" : {\n    \"families\" : {\n      \"bacnet\" : { },\n      \"vendor\" : { }\n    }\n  },\n  \"localnet\" : {\n    \"families\" : {\n      \"ether\" : { },\n      \"ipv4\" : { },\n      \"vendor\" : { },\n      \"bacnet\" : { }\n    }\n  },\n  \"pointset\" : {\n    \"sample_rate_sec\" : 300,\n    \"points\" : {\n      \"filter_alarm_pressure_status\" : {\n        \"ref\" : \"BV11.present_value\",\n        \"units\" : \"No-units\"\n      },\n      \"filter_differential_pressure_setpoint\" : {\n        \"units\" : \"Bars\",\n        \"set_value\" : 98\n      },\n      \"filter_differential_pressure_sensor\" : {\n        \"ref\" : \"AV12.present_value\",\n        \"units\" : \"Degrees-Celsius\"\n      }\n    }\n  }\n}",
    "category" : "device.log",
    "timestamp" : "TIMESTAMP",
    "level" : 100
  }, {
    "message" : "TIMESTAMP",
    "category" : "device.log",
    "timestamp" : "TIMESTAMP",
    "level" : 200
  }, {
    "message" : "value of noWriteback: false",
    "category" : "device.log",
    "timestamp" : "TIMESTAMP",
    "level" : 100
  }, {
    "message" : "value of noWriteback: false",
    "category" : "device.log",
    "timestamp" : "TIMESTAMP",
    "level" : 100
  }, {
    "message" : "value of noWriteback: false",
    "category" : "device.log",
    "timestamp" : "TIMESTAMP",
    "level" : 100
  }, {
    "message" : "success",
    "category" : "system.config.apply",
    "timestamp" : "TIMESTAMP",
    "level" : 300
  }, {
    "message" : "State update defer 1997ms",
    "category" : "device.log",
    "timestamp" : "TIMESTAMP",
    "level" : 100
  }, {
    "message" : "State update defer -1ms",
    "category" : "device.log",
    "timestamp" : "TIMESTAMP",
    "level" : 100
  }, {
    "message" : "Update state TIMESTAMP",
    "category" : "device.log",
    "timestamp" : "TIMESTAMP",
    "level" : 200
  }, {
    "message" : "State update AHU-1 (blob_update_unreachable_url)",
    "detail" : "{\n  \"timestamp\" : \"TIMESTAMP\",\n      \"level\" : 300\n    }\n  },\n  \"discovery\" : {\n    \"families\" : { }\n  },\n  \"localnet\" : {\n    \"families\" : {\n      \"ether\" : {\n        \"addr\" : \"42:01:ac:11:23:ac\"\n      },\n      \"ipv4\" : {\n        \"addr\" : \"172.17.35.172\"\n      },\n      \"vendor\" : {\n        \"addr\" : \"28179023\"\n      },\n      \"bacnet\" : {\n        \"addr\" : \"27312\"\n      }\n    }\n  },\n  \"pointset\" : {\n    \"points\" : {\n      \"filter_alarm_pressure_status\" : {\n        \"units\" : \"No-units\"\n      },\n      \"filter_differential_pressure_setpoint\" : {\n        \"units\" : \"Bars\",\n        \"value_state\" : \"applied\"\n      },\n      \"filter_differential_pressure_sensor\" : {\n        \"units\" : \"Degrees-Celsius\"\n      }\n    }\n  }\n}",
    "category" : "device.log",
    "timestamp" : "TIMESTAMP",
    "level" : 100
  }, {
    "message" : "success",
    "category" : "system.config.receive",
    "timestamp" : "TIMESTAMP",
    "level" : 100
  }, {
    "message" : "success",
    "category" : "system.config.parse",
    "timestamp" : "TIMESTAMP",
    "level" : 100
  }, {
    "message" : "State update defer -1313ms",
    "category" : "device.log",
    "timestamp" : "TIMESTAMP",
    "level" : 100
  }, {
    "message" : "Device AHU-1 config handler",
    "category" : "device.log",
    "timestamp" : "TIMESTAMP",
    "level" : 200
  }, {
    "message" : "State update AHU-1 (blob_update_unreachable_url)",
    "detail" : "{\n  \"timestamp\" : \"TIMESTAMP\",\n      \"level\" : 100\n    }\n  },\n  \"discovery\" : {\n    \"families\" : { }\n  },\n  \"localnet\" : {\n    \"families\" : {\n      \"ether\" : {\n        \"addr\" : \"42:01:ac:11:23:ac\"\n      },\n      \"ipv4\" : {\n        \"addr\" : \"172.17.35.172\"\n      },\n      \"vendor\" : {\n        \"addr\" : \"28179023\"\n      },\n      \"bacnet\" : {\n        \"addr\" : \"27312\"\n      }\n    }\n  },\n  \"pointset\" : {\n    \"points\" : {\n      \"filter_alarm_pressure_status\" : {\n        \"units\" : \"No-units\"\n      },\n      \"filter_differential_pressure_setpoint\" : {\n        \"units\" : \"Bars\",\n        \"value_state\" : \"applied\"\n      },\n      \"filter_differential_pressure_sensor\" : {\n        \"units\" : \"Degrees-Celsius\"\n      }\n    }\n  }\n}",
    "category" : "device.log",
    "timestamp" : "TIMESTAMP",
    "level" : 100
  }, {
    "message" : "Config update AHU-1 (blob_update_unreachable_url)",
    "detail" : "{\n  \"timestamp\" : \"TIMESTAMP\"\n    },\n    \"testing\" : {\n      \"sequence_name\" : \"blob_update_unreachable_url\",\n      \"transaction_id\" : \"RC:c1b619.00000008\",\n      \"config_base\" : 132\n    }\n  },\n  \"discovery\" : {\n    \"families\" : {\n      \"bacnet\" : { },\n      \"vendor\" : { }\n    }\n  },\n  \"localnet\" : {\n    \"families\" : {\n      \"ether\" : { },\n      \"ipv4\" : { },\n      \"vendor\" : { },\n      \"bacnet\" : { }\n    }\n  },\n  \"pointset\" : {\n    \"sample_rate_sec\" : 300,\n    \"points\" : {\n      \"filter_alarm_pressure_status\" : {\n        \"ref\" : \"BV11.present_value\",\n        \"units\" : \"No-units\"\n      },\n      \"filter_differential_pressure_setpoint\" : {\n        \"units\" : \"Bars\",\n        \"set_value\" : 98\n      },\n      \"filter_differential_pressure_sensor\" : {\n        \"ref\" : \"AV12.present_value\",\n        \"units\" : \"Degrees-Celsius\"\n      }\n    }\n  }\n}",
    "category" : "device.log",
    "timestamp" : "TIMESTAMP",
    "level" : 100
  }, {
    "message" : "TIMESTAMP",
    "category" : "device.log",
    "timestamp" : "TIMESTAMP",
    "level" : 200
  }, {
    "message" : "value of noWriteback: false",
    "category" : "device.log",
    "timestamp" : "TIMESTAMP",
    "level" : 100
  }, {
    "message" : "value of noWriteback: false",
    "category" : "device.log",
    "timestamp" : "TIMESTAMP",
    "level" : 100
  }, {
    "message" : "value of noWriteback: false",
    "category" : "device.log",
    "timestamp" : "TIMESTAMP",
    "level" : 100
  }, {
    "message" : "success",
    "category" : "system.config.apply",
    "timestamp" : "TIMESTAMP",
    "level" : 300
  }, {
    "message" : "State update defer 1995ms",
    "category" : "device.log",
    "timestamp" : "TIMESTAMP",
    "level" : 100
  }, {
    "message" : "success",
    "category" : "system.config.receive",
    "timestamp" : "TIMESTAMP",
    "level" : 100
  }, {
    "message" : "success",
    "category" : "system.config.parse",
    "timestamp" : "TIMESTAMP",
    "level" : 100
  }, {
    "message" : "State update defer 1779ms",
    "category" : "device.log",
    "timestamp" : "TIMESTAMP",
    "level" : 100
  }, {
    "message" : "Device AHU-1 config handler",
    "category" : "device.log",
    "timestamp" : "TIMESTAMP",
    "level" : 200
  }, {
    "message" : "Config update AHU-1 (blob_update_unreachable_url)",
    "detail" : "{\n  \"timestamp\" : \"TIMESTAMP\"\n    },\n    \"testing\" : {\n      \"sequence_name\" : \"blob_update_unreachable_url\",\n      \"transaction_id\" : \"RC:c1b619.0000000c\",\n      \"config_base\" : 133\n    }\n  },\n  \"discovery\" : {\n    \"families\" : {\n      \"bacnet\" : { },\n      \"vendor\" : { }\n    }\n  },\n  \"localnet\" : {\n    \"families\" : {\n      \"ether\" : { },\n      \"ipv4\" : { },\n      \"vendor\" : { },\n      \"bacnet\" : { }\n    }\n  },\n  \"pointset\" : {\n    \"sample_rate_sec\" : 300,\n    \"points\" : {\n      \"filter_alarm_pressure_status\" : {\n        \"ref\" : \"BV11.present_value\",\n        \"units\" : \"No-units\"\n      },\n      \"filter_differential_pressure_setpoint\" : {\n        \"units\" : \"Bars\",\n        \"set_value\" : 98\n      },\n      \"filter_differential_pressure_sensor\" : {\n        \"ref\" : \"AV12.present_value\",\n        \"units\" : \"Degrees-Celsius\"\n      }\n    }\n  }\n}",
    "category" : "device.log",
    "timestamp" : "TIMESTAMP",
    "level" : 100
  }, {
    "message" : "TIMESTAMP",
    "category" : "device.log",
    "timestamp" : "TIMESTAMP",
    "level" : 200
  }, {
    "message" : "value of noWriteback: false",
    "category" : "device.log",
